name: Daily View Buff

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: 

jobs:
  visit-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Buff Views
        run: |
          for i in {1..50}; do
            curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" -s "https://visitor-badge.laobi.icu/badge?page_id=kichirou244.kichirou244" > /dev/null
            echo "Hit $i dispatched"
            sleep 1
          done
